meta_title: "SOS Food"
meta_description: "Trouvez un repas solidaire. Simple comme un SMS"
meta_image: "soup_kitchen_2.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@SOSFoodorg" # indispensable pour les Twitter Cards
